### PR TITLE
[I] Bump IntelliJ version to 2019.2.3

### PR DESCRIPTION
**Pull request by tobous**

### CODE REVIEW

**Comment by tobous** [comment]
@m273d15 DockerHub hasn't spawned any of the build jobs for this PR yet. Is there anything I missed or does it just take forever to do anything?

**Comment by tobous** [comment]
Ok, it just seem to take a while....

**Comment by m273d15** [comment]
The triggers are very slow.
We use this mechanism only a few times a year. Therefore, I never changed it to Actions

**Comment by tobous** [comment]
Does ist still offer a benefit to include the dependencies in the docker file? It would be nice to unify the dependency handling (i.e. also pull the necessary IDE instances the same way the normal build does) to avoid such issues in the future.

**Pull request merged**
