### PR TITLE
[Build] CI images for build & test and stf test

### PR DESCRIPTION
**Pull request by m273d15**
* Dockerfile.build_test defines the
  image which is used for the ant build and the
  junit test execution.
  The main setup is processed by src/setup_saros_test.sh.

* Dockerfile.stf_test_master defines the
  image which is used to trigger the stf tests.
  The main setup is processed by src/setup_stf_master.sh.

* Dockerfile.stf_test_slave defines the
  image which is used to execute the stf tests.
  The main setup is processed by src/setup_stf_slave.sh.

* src/uri_env.sh contains all external dependencies which
  has to be downloaded.

* src/setup_utils.sh provides methods to download and setup
  the external dependencies.

### CODE REVIEW

**Comment by fzieris** [comment]
I'd like to see tags in commit messages, even though most of the commits in this repository will probably be [BUILD] or [DOC].

Is this repo already configured properly so that pull requests are squashed and rebased upon merging?

**Comment by m273d15** [comment]
I will add the tag [BUILD]. I disabled all merge options except ["Squash and merge"](https://help.github.com/articles/about-pull-request-merges/).

**Comment by m273d15** [comment]
Added tag to PR subject and commit

**Comment by tobous** [comment]
Currently (at least when I last checked), it is only set to squash merging.

I have a more general question about squashing pull requests?
Currently, I can create multiple changes that depend on earlier changes still in review. This allows me to split larger patches into multiple changes to make them easier to review/understand.
If I would like to recreate this behavior (creating multiple "changes" that are dependent on each other) with GitHub, I would either 
- have to include them all in a single pull request. This would make pull requests a lot larger and would mean that we would loose a lot of detail/separation of concern when squashing.

or

- create multiple pull requests, one for each "change". I don't know if dependent pull requests are possible/how this would be handled by GitHub.

As a current example: I am (still) working on a new implementation for annotations in Saros/I. The patch is currently about 1600 loc. I did not create commits while working on it as the design changed a lot in different ways, which would have created a lot of hassle and useless commits that would have mostly been thrown out/rewritten later on. To push this huge patch to gerrit, I would split it into a chain of gerrit changes.

How should I handle this with GitHub? Should this really create a **single** commit of 1600 lines due to squashing? This would make it very hard to understand after the fact and would also create a very large commit message.

What are your thoughts about this issue? Am I missing another option to recreate my current workflow?

**Comment by m273d15** [comment]
I think you can also create stacked changes in GitHub, but without an automated rebase and dependency management.

My first idea is the following workflow:
* Implement your change based on master
* Push changes to a new remote branch test1 (that is forked from master)
* Implement your changes based on test1
* Push changes to a new remote branch test2 (that is forked from test1)
... and so on

If you have to change something in branch testX you have also to rebase all testN (with N > X).
E.g. if 4 test branches are created and test2 has to be modified. Merge changes into test3, then rebase state of test3 into test4.

Create Pull Request as follows:
* Merge test1 into master
* Merge test2 into test1
...

Merge Pull Request as follow:
* Merge bottom up (starting with test1)
* If testX is merged, rebase test2 and change PR target/base to master
* Merge next PR
...

**Comment by tobous** [comment]
What is the status of this pull request? Is it still needed/current?

**Pull request merged**
